// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VTB_WASM_TOP.cpp"
#include "VTB_WASM_TOP___024root__DepSet_h215b9c62__0.cpp"
#include "VTB_WASM_TOP___024root__DepSet_h16382069__0.cpp"
#include "VTB_WASM_TOP__Trace__0.cpp"
#include "VTB_WASM_TOP__ConstPool_0.cpp"
#include "VTB_WASM_TOP___024root__Slow.cpp"
#include "VTB_WASM_TOP___024root__DepSet_h215b9c62__0__Slow.cpp"
#include "VTB_WASM_TOP___024root__DepSet_h16382069__0__Slow.cpp"
#include "VTB_WASM_TOP__Syms.cpp"
#include "VTB_WASM_TOP__Trace__0__Slow.cpp"
#include "VTB_WASM_TOP__TraceDecls__0__Slow.cpp"
